<a href="https://colab.research.google.com/github/mjiii25/22-1_DLAI/blob/main/HW1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [4]:
import numpy as np
import matplotlib.pyplot as plt
import tensorflow as tf

In [8]:
a, y = tf.constant(2.0), tf.constant(8.0)
x = tf.Variable(10.0) # In practice, we start with a random value
loss = tf.math.abs(a * x - y)
loss

<tf.Tensor: shape=(), dtype=float32, numpy=12.0>

In [9]:
# UDF for training

def train_func():
    with tf.GradientTape() as tape:
        loss = tf.math.abs(a * x - y)

    # calculate gradient

    dx =  tape.gradient(loss, x)
    print('x = {}, dx = {:.2f}'.format(x.numpy(), dx))

    # update x <- x - dx
    x.assign(x - dx)

In [10]:
# Run train_func() UDF repeately

for i in range(4):

    train_func()

x = 10.0, dx = 2.00
x = 8.0, dx = 2.00
x = 6.0, dx = 2.00
x = 4.0, dx = 0.00


---------------------------------------------------------------------------------------




In [11]:
input_var = tf.Variable(initial_value=3.)
with tf.GradientTape() as tape:
   result = tf.square(input_var)
gradient = tape.gradient(result, input_var)

In [12]:
gradient

<tf.Tensor: shape=(), dtype=float32, numpy=6.0>

In [22]:
## self practice
input_var = tf.Variable(initial_value=3.)
with tf.GradientTape() as tape:
   result = tf.square(input_var)
   print(result)

tf.Tensor(9.0, shape=(), dtype=float32)


In [23]:
tape.gradient(result, input_var)

<tf.Tensor: shape=(), dtype=float32, numpy=6.0>

In [17]:
tape.gradient?

## HW 1 
Answer folloing questions using tensorflow's gradient tape.  

EX)
```
input_var = tf.Variable(initial_value=3.)
with tf.GradientTape() as tape:
   result = tf.square(input_var)
gradient = tape.gradient(result, input_var)
```

### Q1 Differentiate $y = x^2 + 3x + 1$ with respect to a scalar variable $x$.

In [ ]:
import tensorflow as tf

In [32]:
input_var = tf.Variable(initial_value=3.)

with tf.GradientTape() as tape:
   result = tf.square(input_var) + 3 * input_var + 1
gradient = tape.gradient(result, input_var)

gradient

<tf.Tensor: shape=(), dtype=float32, numpy=9.0>

### Q2 Differentiate $y = X^3 + 3X + 5$ with respect to a 2 by 2 matrix variable $X$.

In [35]:
input_var = tf.Variable(initial_value=3.)

with tf.GradientTape() as tape:
   result = input_var**3 + 3 * input_var + 5
gradient = tape.gradient(result, input_var)

gradient

<tf.Tensor: shape=(), dtype=float32, numpy=30.0>

### Q3 Differentiate $z = X^3 y^2 + 3X + 2Xy + 1$ with respect to a 2 by 2 matrix variable $X$ and a scalar variable $y$.

In [46]:
input_X = tf.Variable(initial_value = 1., name = 'input_X')
input_y = tf.Variable(initial_value = 1., name = 'input_y')

with tf.GradientTape() as tape:
  result = input_X**3 * input_y**2 + 3 * input_X + 2 * input_X * input_y + 1
gradient = tape.gradient(result, input_X, input_y)

gradient

<tf.Tensor: shape=(), dtype=float32, numpy=8.0>