<a href="https://colab.research.google.com/github/mjiii25/22-1_DLAI/blob/main/HW1_20183127.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## HW 1 
Answer folloing questions using tensorflow's gradient tape.  

EX)
```
input_var = tf.Variable(initial_value=3.)
with tf.GradientTape() as tape:
   result = tf.square(input_var)
gradient = tape.gradient(result, input_var)
```

### Q1 Differentiate $y = x^2 + 3x + 1$ with respect to a scalar variable $x$.

In [ ]:
import tensorflow as tf

In [ ]:
input_var = tf.Variable(initial_value=3.)

with tf.GradientTape() as tape:
   result = tf.square(input_var) + 3 * input_var + 1
gradient = tape.gradient(result, input_var)

gradient

<tf.Tensor: shape=(), dtype=float32, numpy=9.0>

### Q2 Differentiate $y = X^3 + 3X + 5$ with respect to a 2 by 2 matrix variable $X$.

In [ ]:
input_var = tf.Variable(initial_value=3.)

with tf.GradientTape() as tape:
   result = input_var**3 + 3 * input_var + 5
gradient = tape.gradient(result, input_var)

gradient

<tf.Tensor: shape=(), dtype=float32, numpy=30.0>

### Q3 Differentiate $z = X^3 y^2 + 3X + 2Xy + 1$ with respect to a 2 by 2 matrix variable $X$ and a scalar variable $y$.

In [ ]:
input_X = tf.Variable(initial_value = 2., name = 'input_X')
input_y = tf.Variable(initial_value = 3., name = 'input_y')

with tf.GradientTape() as tape:
  result = input_X**3 * input_y**2 + 3 * input_X + 2 * input_X * input_y + 1
gradient = tape.gradient(result, [input_X, input_y])

gradient

[<tf.Tensor: shape=(), dtype=float32, numpy=117.0>,
 <tf.Tensor: shape=(), dtype=float32, numpy=52.0>]